# Generated by Django 2.0.5 on 2018-05-28 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180527_1409'),
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('title', models.CharField(max_length=60)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 5, 28, 8, 25, 51, 477703, tzinfo=utc))),
                ('name_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('http_link', models.URLField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.RedditUser')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='subreddit',
            field=models.ForeignKey(default='main', on_delete=django.db.models.deletion.CASCADE, to='reddit.Subreddit'),
            preserve_default=False,
        ),
    ]
