# Generated by Django 2.0.5 on 2018-05-28 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20180528_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 8, 31, 41, 818280, tzinfo=utc)),
        ),
    ]
