# Generated by Django 2.0.5 on 2018-05-28 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_auto_20180528_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='description',
            field=models.TextField(default='asdf', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subreddit',
            name='sub_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 12, 6, 35, 449031, tzinfo=utc)),
        ),
    ]
