# Generated by Django 2.0.5 on 2018-05-28 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_auto_20180528_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='http_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 18, 39, 39, 321799, tzinfo=utc)),
        ),
    ]
