# Generated by Django 2.0.5 on 2018-05-30 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0005_auto_20180528_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='admin_name',
            field=models.CharField(default='zbiku', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='sub_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 8, 42, 3, 156309, tzinfo=utc)),
        ),
    ]
